declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';
  
  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  }
  
  export type Icon = FC<IconProps>;
  
  // Export all possible icon variants
  // Since lucide-react exports hundreds of icons, we'll use a more flexible approach
  
  // Common icons used in the project
  export const Loader2Icon: Icon;
  export const Loader2: Icon;
  export const ArrowUpDown: Icon;
  export const ArrowUp: Icon;
  export const ArrowDown: Icon;
  export const ArrowRight: Icon;
  export const ArrowLeft: Icon;
  export const FileDown: Icon;
  export const Upload: Icon;
  export const Edit2Icon: Icon;
  export const Edit2: Icon;
  export const DownloadIcon: Icon;
  export const Download: Icon;
  export const Trash2Icon: Icon;
  export const Trash2: Icon;
  export const TrashIcon: Icon;
  export const Trash: Icon;
  export const SearchIcon: Icon;
  export const Search: Icon;
  export const FilterIcon: Icon;
  export const Filter: Icon;
  export const ChevronDownIcon: Icon;
  export const ChevronDown: Icon;
  export const ChevronUp: Icon;
  export const ChevronLeft: Icon;
  export const ChevronRight: Icon;
  export const XIcon: Icon;
  export const X: Icon;
  export const CalendarIcon: Icon;
  export const Calendar: Icon;
  export const FilePenIcon: Icon;
  export const CheckCircle2: Icon;
  export const CheckCircle: Icon;
  export const Check: Icon;
  export const ChevronsUpDown: Icon;
  export const Plus: Icon;
  export const PlusIcon: Icon;
  export const PlusCircle: Icon;
  export const Minus: Icon;
  export const Printer: Icon;
  export const Replace: Icon;
  export const Calculator: Icon;
  export const MinusIcon: Icon;
  export const Edit: Icon;
  export const EditIcon: Icon;
  export const Settings: Icon;
  export const SettingsIcon: Icon;
  export const LogOut: Icon;
  export const Menu: Icon;
  export const MenuIcon: Icon;
  export const MoreVertical: Icon;
  export const MoreHorizontal: Icon;
  export const Eye: Icon;
  export const EyeIcon: Icon;
  export const EyeOff: Icon;
  export const EyeOffIcon: Icon;
  export const Copy: Icon;
  export const CopyIcon: Icon;
  export const ExternalLink: Icon;
  export const AlertCircle: Icon;
  export const AlertCircleIcon: Icon;
  export const Info: Icon;
  export const InfoIcon: Icon;
  export const HelpCircle: Icon;
  export const XCircle: Icon;
  export const AlertTriangle: Icon;
  export const DollarSign: Icon;
  export const DollarSignIcon: Icon;
  export const TrendingUp: Icon;
  export const TrendingDown: Icon;
  export const Users: Icon;
  export const UserIcon: Icon;
  export const User: Icon;
  export const UserPlus: Icon;
  export const UserMinus: Icon;
  export const UserCheck: Icon;
  export const Package: Icon;
  export const PackageIcon: Icon;
  export const Package2: Icon;
  export const Package2Icon: Icon;
  export const ShoppingCart: Icon;
  export const ShoppingCartIcon: Icon;
  export const ShoppingBag: Icon;
  export const ShoppingBagIcon: Icon;
  export const LayoutDashboard: Icon;
  export const LayoutDashboardIcon: Icon;
  export const UsersIcon: Icon;
  export const LogOutIcon: Icon;
  export const BarChart: Icon;
  export const BarChartIcon: Icon;
  export const PieChart: Icon;
  export const Activity: Icon;
  export const Home: Icon;
  export const HomeIcon: Icon;
  export const FileText: Icon;
  export const FileTextIcon: Icon;
  export const File: Icon;
  export const FileIcon: Icon;
  export const Folder: Icon;
  export const FolderIcon: Icon;
  export const Save: Icon;
  export const SaveIcon: Icon;
  export const RefreshCw: Icon;
  export const RotateCcw: Icon;
  export const Maximize: Icon;
  export const Maximize2: Icon;
  export const Minimize: Icon;
  export const Minimize2: Icon;
  export const ZoomIn: Icon;
  export const ZoomOut: Icon;
  export const Clock: Icon;
  export const ClockIcon: Icon;
  export const Mail: Icon;
  export const MailIcon: Icon;
  export const Phone: Icon;
  export const PhoneIcon: Icon;
  export const Lock: Icon;
  export const LockIcon: Icon;
  export const Unlock: Icon;
  export const Key: Icon;
  export const KeyIcon: Icon;
  export const Bell: Icon;
  export const BellIcon: Icon;
  export const BellOff: Icon;
  export const Star: Icon;
  export const StarIcon: Icon;
  export const Heart: Icon;
  export const HeartIcon: Icon;
  export const Share: Icon;
  export const Share2: Icon;
  export const ShareIcon: Icon;
  export const Link: Icon;
  export const LinkIcon: Icon;
  export const Paperclip: Icon;
  export const Image: Icon;
  export const ImageIcon: Icon;
  export const Video: Icon;
  export const VideoIcon: Icon;
  export const Music: Icon;
  export const Mic: Icon;
  export const Camera: Icon;
  export const CameraIcon: Icon;
  export const MapPin: Icon;
  export const Navigation: Icon;
  export const Globe: Icon;
  export const GlobeIcon: Icon;
  export const Wifi: Icon;
  export const WifiOff: Icon;
  export const Battery: Icon;
  export const Zap: Icon;
  export const Sun: Icon;
  export const SunIcon: Icon;
  export const Moon: Icon;
  export const MoonIcon: Icon;
  export const CloudRain: Icon;
  export const Cloud: Icon;
  export const Umbrella: Icon;
  export const Award: Icon;
  export const Gift: Icon;
  export const Tag: Icon;
  export const TagIcon: Icon;
  export const Bookmark: Icon;
  export const Flag: Icon;
  export const Target: Icon;
  export const Crosshair: Icon;
  export const Sliders: Icon;
  export const SlidersIcon: Icon;
  export const Grid: Icon;
  export const GridIcon: Icon;
  export const List: Icon;
  export const ListIcon: Icon;
  export const Layout: Icon;
  export const Columns: Icon;
  export const Sidebar: Icon;
  export const Square: Icon;
  export const Circle: Icon;
  export const Triangle: Icon;
  export const Hexagon: Icon;
  export const Box: Icon;
  export const Archive: Icon;
  export const Inbox: Icon;
  export const Send: Icon;
  export const SendIcon: Icon;
  export const MessageCircle: Icon;
  export const MessageSquare: Icon;
  export const AtSign: Icon;
  export const Hash: Icon;
  export const Percent: Icon;
  export const Divide: Icon;
  export const Equal: Icon;
  
  // Catch-all for any other icons that might be used
  const lucideReact: {
    [key: string]: Icon;
  };
  
  export default lucideReact;
}
